root_path: "/home/bhernandez/Documents/deepstream/workspace"

marauders:
  enable: true
  display: false
  map_path: "projections/map.png"
  transforms_path: "projections/transforms.yml"
  trajs_dir: "experiments/exp040cam360s_first_run/trajDumps"
  gt_path: "datasets/orig/ground_truth.txt"
  cams_dir: "experiments/exp040cam360s_first_run/camInfo"
  reproj_pixel_thres: 150
  traj_window_size: 240
  fps: 30
  show:
    gt: true
    traj: true
    # cam_loc: true
    # cam_dir: true
    # cam_fov: true
    # cameras: 
    # - 1 
    # - 2 
    # - 3 
    # - 4
    # - 5
    # - 6
    # - 7
    # cameras: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39

# ffmpeg -i test.avi -c:v libx264 -crf 23 output.mp4

# marauders:
#   enable: true
#   # display: true
#   map_path: "projections/map.png"
#   transforms_path: "projections/transforms.yml"
#   # Assumed trajs_dir/trajDump_Stream_%d.txt. If absent, then only GT considered.
#   # trajs_dir: "trajDumps"
#   trajs_dir: "triesMultipleStrings/conf4"
#   gt_path: "dataset/ground_truth.txt"
#   # Assumed cams_dir/Warehouse_Synthetic_Cam%03d.yml
#   cams_dir: "dataset/camInfo"
#   # pixel threshold for reprojection size of the bounding box ofr FOV
#   reproj_pixel_thres: 150
#   traj_window_size: 240
#   fps: 30
#   show: 
#     gt: true
#     traj: true
#     cam_loc: true
#     cam_dir: true
#     # cam_fov: true
#     cameras:
#      - 1
#      - 38
#      - 48
#      - 74

# overlay:
#   display: true
#   traj_window_size: 120
#   show:
#     tracker_output_bbox: false
#     tracker_output_bbox_center: true
#     tracker_output_trajectory: true
#     tracker_output_convex_hull: true
#     use_foot_location: true
#     mdat_output: false
#     frame_nb: true
#   tracking:
#     type: "all"
#     id: 0
#   bbox_frame:
#     width: 1920
#     height: 1080
